"""
Shared constants for vcf2maf Python port.
Mirrors the data structures in vcf2maf.pl / maf2vcf.pl.
"""

# ---------------------------------------------------------------------------
# VEP consequence terms, ordered from most to least severe.
# Ties broken left-to-right; first match wins when picking the "best" effect.
# ---------------------------------------------------------------------------
VEP_CONSEQUENCE_PRIORITY = {
    "transcript_ablation":            1,
    "exon_loss_variant":              1,
    "splice_donor_variant":           2,
    "splice_acceptor_variant":        2,
    "stop_gained":                    3,
    "frameshift_variant":             3,
    "stop_lost":                      3,
    "start_lost":                     4,
    "initiator_codon_variant":        4,
    "disruptive_inframe_insertion":   5,
    "disruptive_inframe_deletion":    5,
    "inframe_insertion":              5,
    "inframe_deletion":               5,
    "missense_variant":               6,
    "conservative_missense_variant":  6,
    "rare_amino_acid_variant":        6,
    "transcript_amplification":       7,
    "splice_region_variant":          8,
    "stop_retained_variant":          9,
    "synonymous_variant":             9,
    "incomplete_terminal_codon_variant": 10,
    "coding_sequence_variant":        10,
    "mature_miRNA_variant":           11,
    "exon_variant":                   11,
    "5_prime_UTR_variant":            12,
    "3_prime_UTR_variant":            12,
    "non_coding_exon_variant":        13,
    "non_coding_transcript_exon_variant": 13,
    "non_coding_transcript_variant":  14,
    "nc_transcript_variant":          14,
    "intron_variant":                 14,
    "INTRAGENIC":                     14,
    "intragenic_variant":             14,
    "NMD_transcript_variant":         15,
    "upstream_gene_variant":          16,
    "downstream_gene_variant":        16,
    "TFBS_ablation":                  17,
    "TFBS_amplification":             17,
    "TF_binding_site_variant":        17,
    "regulatory_region_ablation":     17,
    "regulatory_region_amplification": 17,
    "regulatory_region_variant":      17,
    "regulatory_region":              17,
    "feature_elongation":             18,
    "feature_truncation":             18,
    "intergenic_variant":             19,
    "intergenic_region":              19,
    "":                               20,
}

# ---------------------------------------------------------------------------
# Map VEP consequence → MAF Variant_Classification
# ---------------------------------------------------------------------------
VEP_TO_MAF_VARIANT_CLASS = {
    "splice_acceptor_variant":             "Splice_Site",
    "splice_donor_variant":                "Splice_Site",
    "transcript_ablation":                 "Splice_Site",
    "exon_loss_variant":                   "Splice_Site",
    "stop_gained":                         "Nonsense_Mutation",
    "frameshift_variant":                  "Frame_Shift",
    "stop_lost":                           "Nonstop_Mutation",
    "initiator_codon_variant":             "Translation_Start_Site",
    "start_lost":                          "Translation_Start_Site",
    "inframe_insertion":                   "In_Frame_Ins",
    "disruptive_inframe_insertion":        "In_Frame_Ins",
    "inframe_deletion":                    "In_Frame_Del",
    "disruptive_inframe_deletion":         "In_Frame_Del",
    "missense_variant":                    "Missense_Mutation",
    "conservative_missense_variant":       "Missense_Mutation",
    "rare_amino_acid_variant":             "Missense_Mutation",
    "transcript_amplification":            "Intron",
    "splice_region_variant":               "Splice_Region",
    "stop_retained_variant":               "Silent",
    "synonymous_variant":                  "Silent",
    "incomplete_terminal_codon_variant":   "Silent",
    "coding_sequence_variant":             "Missense_Mutation",
    "mature_miRNA_variant":                "RNA",
    "exon_variant":                        "RNA",
    "5_prime_UTR_variant":                 "5'UTR",
    "3_prime_UTR_variant":                 "3'UTR",
    "non_coding_exon_variant":             "RNA",
    "non_coding_transcript_exon_variant":  "RNA",
    "non_coding_transcript_variant":       "RNA",
    "nc_transcript_variant":               "RNA",
    "intron_variant":                      "Intron",
    "INTRAGENIC":                          "Intron",
    "intragenic_variant":                  "Intron",
    "NMD_transcript_variant":              "Silent",
    "upstream_gene_variant":               "5'Flank",
    "downstream_gene_variant":             "3'Flank",
    "TF_binding_site_variant":             "IGR",
    "regulatory_region_variant":           "IGR",
    "regulatory_region":                   "IGR",
    "intergenic_variant":                  "IGR",
    "intergenic_region":                   "IGR",
    "feature_elongation":                  "Targeted_Region",
    "feature_truncation":                  "Targeted_Region",
    "TFBS_ablation":                       "Targeted_Region",
    "TFBS_amplification":                  "Targeted_Region",
    "regulatory_region_ablation":          "Targeted_Region",
    "regulatory_region_amplification":     "Targeted_Region",
}

# ---------------------------------------------------------------------------
# Required MAF columns, in order (GDC MAF v1.0.0 / TCGA standard)
# ---------------------------------------------------------------------------
MAF_COLUMNS = [
    "Hugo_Symbol",
    "Entrez_Gene_Id",
    "Center",
    "NCBI_Build",
    "Chromosome",
    "Start_Position",
    "End_Position",
    "Strand",
    "Variant_Classification",
    "Variant_Type",
    "Reference_Allele",
    "Tumor_Seq_Allele1",
    "Tumor_Seq_Allele2",
    "dbSNP_RS",
    "dbSNP_Val_Status",
    "Tumor_Sample_Barcode",
    "Matched_Norm_Sample_Barcode",
    "Match_Norm_Seq_Allele1",
    "Match_Norm_Seq_Allele2",
    "Tumor_Validation_Allele1",
    "Tumor_Validation_Allele2",
    "Match_Norm_Validation_Allele1",
    "Match_Norm_Validation_Allele2",
    "Verification_Status",
    "Validation_Status",
    "Mutation_Status",
    "Sequencing_Phase",
    "Sequence_Source",
    "Validation_Method",
    "Score",
    "BAM_File",
    "Sequencer",
    "Tumor_Sample_UUID",
    "Matched_Norm_Sample_UUID",
    "HGVSc",
    "HGVSp",
    "HGVSp_Short",
    "Transcript_ID",
    "Exon_Number",
    "t_depth",
    "t_ref_count",
    "t_alt_count",
    "n_depth",
    "n_ref_count",
    "n_alt_count",
    "all_effects",
    "Allele",
    "Gene",
    "Feature",
    "Feature_type",
    "Consequence",
    "cDNA_position",
    "CDS_position",
    "Protein_position",
    "Amino_acids",
    "Codons",
    "Existing_variation",
    "ALLELE_NUM",
    "DISTANCE",
    "STRAND_VEP",
    "SYMBOL",
    "SYMBOL_SOURCE",
    "HGNC_ID",
    "BIOTYPE",
    "CANONICAL",
    "CCDS",
    "ENSP",
    "SWISSPROT",
    "TREMBL",
    "UNIPARC",
    "RefSeq",
    "SIFT",
    "PolyPhen",
    "EXON",
    "INTRON",
    "DOMAINS",
    "gnomAD_AF",
    "gnomAD_AFR_AF",
    "gnomAD_AMR_AF",
    "gnomAD_ASJ_AF",
    "gnomAD_EAS_AF",
    "gnomAD_FIN_AF",
    "gnomAD_NFE_AF",
    "gnomAD_OTH_AF",
    "gnomAD_SAS_AF",
    "gnomADe_AF",
    "gnomADe_AFR_AF",
    "gnomADe_AMR_AF",
    "gnomADe_ASJ_AF",
    "gnomADe_EAS_AF",
    "gnomADe_FIN_AF",
    "gnomADe_NFE_AF",
    "gnomADe_OTH_AF",
    "gnomADe_SAS_AF",
    "CLIN_SIG",
    "SOMATIC",
    "PUBMED",
    "MOTIF_NAME",
    "MOTIF_POS",
    "HIGH_INF_POS",
    "MOTIF_SCORE_CHANGE",
    "IMPACT",
    "PICK",
    "VARIANT_CLASS",
    "TSL",
    "HGVS_OFFSET",
    "PHENO",
    "GENE_PHENO",
    "FILTER",
    "flanking_bps",
    "variant_id",
    "variant_qual",
    "ExAC_AF",
    "ExAC_AF_AFR",
    "ExAC_AF_AMR",
    "ExAC_AF_EAS",
    "ExAC_AF_FIN",
    "ExAC_AF_NFE",
    "ExAC_AF_OTH",
    "ExAC_AF_SAS",
    "vcf_id",
    "vcf_qual",
    "ExAC_AF_Adj",
    "ExAC_AC_AN_Adj",
    "ExAC_AC_AN",
    "ExAC_AC_AN_AFR",
    "ExAC_AC_AN_AMR",
    "ExAC_AC_AN_EAS",
    "ExAC_AC_AN_FIN",
    "ExAC_AC_AN_NFE",
    "ExAC_AC_AN_OTH",
    "ExAC_AC_AN_SAS",
    "ExAC_FILTER",
]

# VEP CSQ fields that vcf2maf expects (in order that VEP outputs them).
# These are matched against the actual ##INFO=<ID=CSQ,...,Description="...Format: ..."> header.
DEFAULT_VEP_FIELDS = [
    "Allele",
    "Consequence",
    "IMPACT",
    "SYMBOL",
    "Gene",
    "Feature_type",
    "Feature",
    "BIOTYPE",
    "EXON",
    "INTRON",
    "HGVSc",
    "HGVSp",
    "cDNA_position",
    "CDS_position",
    "Protein_position",
    "Amino_acids",
    "Codons",
    "Existing_variation",
    "ALLELE_NUM",
    "DISTANCE",
    "STRAND",
    "FLAGS",
    "VARIANT_CLASS",
    "SYMBOL_SOURCE",
    "HGNC_ID",
    "CANONICAL",
    "MANE_SELECT",
    "MANE_PLUS_CLINICAL",
    "TSL",
    "APPRIS",
    "CCDS",
    "ENSP",
    "SWISSPROT",
    "TREMBL",
    "UNIPARC",
    "RefSeq",
    "GENE_PHENO",
    "SIFT",
    "PolyPhen",
    "DOMAINS",
    "miRNA",
    "AF",
    "AFR_AF",
    "AMR_AF",
    "EAS_AF",
    "EUR_AF",
    "SAS_AF",
    "AA_AF",
    "EA_AF",
    "gnomAD_AF",
    "gnomAD_AFR_AF",
    "gnomAD_AMR_AF",
    "gnomAD_ASJ_AF",
    "gnomAD_EAS_AF",
    "gnomAD_FIN_AF",
    "gnomAD_NFE_AF",
    "gnomAD_OTH_AF",
    "gnomAD_SAS_AF",
    "MAX_AF",
    "MAX_AF_POPS",
    "gnomADe_AF",
    "gnomADe_AFR_AF",
    "gnomADe_AMR_AF",
    "gnomADe_ASJ_AF",
    "gnomADe_EAS_AF",
    "gnomADe_FIN_AF",
    "gnomADe_NFE_AF",
    "gnomADe_OTH_AF",
    "gnomADe_SAS_AF",
    "CLIN_SIG",
    "SOMATIC",
    "PHENO",
    "PUBMED",
    "MOTIF_NAME",
    "MOTIF_POS",
    "HIGH_INF_POS",
    "MOTIF_SCORE_CHANGE",
    "TRANSCRIPTION_FACTORS",
    "CADD_RAW",
    "CADD_PHRED",
    "PICK",
    "HGVS_OFFSET",
]

# Biotype priority for transcript selection (higher = preferred)
BIOTYPE_PRIORITY = {
    "protein_coding":                      1,
    "LRG_gene":                            2,
    "IG_C_gene":                           2,
    "IG_D_gene":                           2,
    "IG_J_gene":                           2,
    "IG_V_gene":                           2,
    "TR_C_gene":                           2,
    "TR_D_gene":                           2,
    "TR_J_gene":                           2,
    "TR_V_gene":                           2,
    "miRNA":                               3,
    "snRNA":                               3,
    "snoRNA":                              3,
    "rRNA":                                3,
    "lincRNA":                             3,
    "lncRNA":                              3,
    "Mt_tRNA":                             4,
    "Mt_rRNA":                             4,
    "antisense":                           5,
    "sense_intronic":                      5,
    "sense_overlapping":                   5,
    "protein_coding_CDS_not_defined":      6,
    "processed_transcript":                6,
    "pseudogene":                          6,
    "processed_pseudogene":                6,
    "polymorphic_pseudogene":              6,
    "retrotransposed":                     6,
    "transcribed_processed_pseudogene":    6,
    "transcribed_unprocessed_pseudogene":  6,
    "transcribed_unitary_pseudogene":      6,
    "translated_processed_pseudogene":     6,
    "translated_unprocessed_pseudogene":   6,
    "TR_J_pseudogene":                     6,
    "TR_V_pseudogene":                     6,
    "unprocessed_pseudogene":              6,
    "retained_intron":                     7,
    "TF_binding_site":                     7,
    "CTCF_binding_site":                   7,
    "promoter_flanking_region":            7,
    "enhancer":                            7,
    "IG_C_pseudogene":                     7,
    "IG_D_pseudogene":                     7,
    "IG_J_pseudogene":                     7,
    "IG_V_pseudogene":                     7,
    "3prime_overlapping_ncrna":            7,
    "misc_RNA":                            7,
    "non_coding":                          7,
    "regulatory_region":                   7,
    "RNase_MRP_RNA":                       7,
    "RNase_P_RNA":                         7,
    "scRNA":                               7,
    "srpRNA":                              7,
    "TEC":                                 7,
    "tRNA":                                7,
    "vaultRNA":                            7,
}
